/**
 * Daily digest email.
 *
 * Pulls the last 24h of qualifying edgar_leads, renders a Solventis-branded
 * HTML email (high-priority first, then medium), and sends it through the
 * self-hosted Postal server's HTTP API.
 */
import { supabase } from "./supabase.js";
import { config, HIGH_PRIORITY_SCORE } from "./config.js";

interface DigestLead {
  company_name: string | null;
  lead_score: number | null;
  sector: string | null;
  business_state: string | null;
  business_city: string | null;
  edgar_url: string | null;
  phone: string | null;
  contact_phone: string | null;
  contact_name: string | null;
  qualified_service: string | null;
  signal_type: string | null;
  outreach_angle: string | null;
  created_at: string | null;
}

const BRAND = "#0b3d5c"; // Solventis deep blue
const ACCENT = "#c9a227"; // gold accent

function esc(v: unknown): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function bestPhone(l: DigestLead): string {
  return l.contact_phone || l.phone || "";
}

function leadRow(l: DigestLead): string {
  const phone = bestPhone(l);
  const loc = [l.business_city, l.business_state].filter(Boolean).join(", ");
  const link = l.edgar_url
    ? `<a href="${esc(l.edgar_url)}" style="color:${BRAND};">View filing</a>`
    : "";
  return `
  <tr>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;">
      <div style="font-weight:600;color:#111;">${esc(l.company_name) || "(unknown company)"}</div>
      <div style="font-size:12px;color:#666;">${esc(l.qualified_service)} &middot; ${esc(l.signal_type)}</div>
      ${l.outreach_angle ? `<div style="font-size:12px;color:#444;margin-top:4px;font-style:italic;">${esc(l.outreach_angle)}</div>` : ""}
    </td>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;text-align:center;">
      <span style="display:inline-block;min-width:34px;padding:4px 8px;border-radius:12px;background:${BRAND};color:#fff;font-weight:700;">${esc(l.lead_score)}</span>
    </td>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;font-size:13px;color:#333;">${esc(l.sector) || "&mdash;"}</td>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;font-size:13px;color:#333;">${esc(loc) || "&mdash;"}</td>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;font-size:13px;color:#333;">${phone ? esc(phone) : "&mdash;"}</td>
    <td style="padding:10px 12px;border-bottom:1px solid #eee;font-size:13px;">${link}</td>
  </tr>`;
}

function section(title: string, color: string, leads: DigestLead[]): string {
  if (leads.length === 0) {
    return `<h2 style="color:${color};font-size:16px;margin:24px 0 8px;">${title} (0)</h2>
      <p style="color:#888;font-size:13px;margin:0 0 8px;">None today.</p>`;
  }
  const header = `
    <tr style="background:#f6f8fa;">
      <th align="left" style="padding:8px 12px;font-size:12px;color:#666;">Company</th>
      <th style="padding:8px 12px;font-size:12px;color:#666;">Score</th>
      <th align="left" style="padding:8px 12px;font-size:12px;color:#666;">Sector</th>
      <th align="left" style="padding:8px 12px;font-size:12px;color:#666;">Location</th>
      <th align="left" style="padding:8px 12px;font-size:12px;color:#666;">Phone</th>
      <th align="left" style="padding:8px 12px;font-size:12px;color:#666;">EDGAR</th>
    </tr>`;
  return `
    <h2 style="color:${color};font-size:16px;margin:24px 0 8px;">${title} (${leads.length})</h2>
    <table width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;border:1px solid #eee;">
      ${header}
      ${leads.map(leadRow).join("")}
    </table>`;
}

function renderHtml(high: DigestLead[], medium: DigestLead[], dateLabel: string): string {
  return `<!doctype html>
<html><body style="margin:0;background:#f0f2f5;font-family:Helvetica,Arial,sans-serif;">
  <div style="max-width:760px;margin:0 auto;background:#fff;">
    <div style="background:${BRAND};padding:20px 24px;">
      <div style="color:#fff;font-size:20px;font-weight:700;letter-spacing:0.5px;">SOLVENTIS</div>
      <div style="color:${ACCENT};font-size:13px;margin-top:2px;">EDGAR Lead Digest &middot; ${esc(dateLabel)}</div>
    </div>
    <div style="padding:8px 24px 24px;">
      <p style="color:#444;font-size:14px;">
        ${high.length + medium.length} new qualifying lead(s) from the last 24 hours.
      </p>
      ${section("High Priority", BRAND, high)}
      ${section("Medium Priority", "#555", medium)}
      <p style="color:#aaa;font-size:11px;margin-top:28px;">
        Generated by edgar-lead-engine. High priority = score &ge; ${HIGH_PRIORITY_SCORE};
        medium = ${config.minLeadScore}&ndash;${HIGH_PRIORITY_SCORE - 1}.
      </p>
    </div>
  </div>
</body></html>`;
}

function renderText(high: DigestLead[], medium: DigestLead[], dateLabel: string): string {
  const line = (l: DigestLead) =>
    `  [${l.lead_score}] ${l.company_name ?? "(unknown)"} — ${l.sector ?? ""} — ${[l.business_city, l.business_state].filter(Boolean).join(", ")} — ${bestPhone(l) || "no phone"} — ${l.edgar_url ?? ""}`;
  return [
    `SOLVENTIS — EDGAR Lead Digest — ${dateLabel}`,
    ``,
    `High Priority (${high.length}):`,
    ...high.map(line),
    ``,
    `Medium Priority (${medium.length}):`,
    ...medium.map(line),
  ].join("\n");
}

export interface DigestResult {
  sent: boolean;
  reason?: string;
  highCount: number;
  mediumCount: number;
}

/** Build and send the daily digest. Returns a result instead of throwing. */
export async function sendDigest(): Promise<DigestResult> {
  if (!config.digestEnabled) {
    return { sent: false, reason: "digest disabled (missing Postal/recipient env)", highCount: 0, mediumCount: 0 };
  }

  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { data, error } = await supabase
    .from("edgar_leads")
    .select(
      "company_name,lead_score,sector,business_state,business_city,edgar_url,phone,contact_phone,contact_name,qualified_service,signal_type,outreach_angle,created_at"
    )
    .gte("created_at", since)
    .gte("lead_score", config.minLeadScore)
    .order("lead_score", { ascending: false });

  if (error) {
    return { sent: false, reason: `query failed: ${error.message}`, highCount: 0, mediumCount: 0 };
  }

  const leads = (data ?? []) as DigestLead[];
  const high = leads.filter((l) => (l.lead_score ?? 0) >= HIGH_PRIORITY_SCORE);
  const medium = leads.filter((l) => (l.lead_score ?? 0) < HIGH_PRIORITY_SCORE);

  const dateLabel = new Date().toLocaleDateString("en-US", {
    timeZone: "America/Chicago",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const subject = `Solventis EDGAR Digest — ${high.length} high / ${medium.length} medium — ${dateLabel}`;
  const html = renderHtml(high, medium, dateLabel);
  const text = renderText(high, medium, dateLabel);

  const body = {
    to: config.digestTo,
    cc: config.digestCc.length > 0 ? config.digestCc : undefined,
    from: config.digestFrom,
    subject,
    html_body: html,
    plain_body: text,
  };

  const res = await fetch(config.postalEndpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Server-API-Key": config.postalApiKey,
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const txt = await res.text();
    return {
      sent: false,
      reason: `Postal HTTP ${res.status}: ${txt.slice(0, 300)}`,
      highCount: high.length,
      mediumCount: medium.length,
    };
  }

  return { sent: true, highCount: high.length, mediumCount: medium.length };
}
